-- 0001_baseline.sql
--
-- Basisschema van Autofiscaliteit: de zes tabellen die tot nu toe enkel in het
-- live Supabase-project bestonden en nergens in de repository waren vastgelegd.
-- Alles is idempotent (create table if not exists / on conflict do nothing),
-- zodat deze migratie veilig op de bestaande database kan draaien.
--
-- Uitvoeren: Supabase → SQL Editor, of `supabase db push`.
--
-- Dit bestand is met de hand geschreven op basis van src/lib/fiscaal/types.ts,
-- omdat het live project niet vanuit deze omgeving bereikbaar is. Heb je de
-- Supabase CLI gekoppeld, draai dan eenmalig `supabase db pull` en vergelijk het
-- resultaat met dit bestand: dat is de enige manier om zeker te zijn dat het
-- schema hier exact overeenkomt met de productiedatabase.

-- ---------------------------------------------------------------------------
-- Referentiedata: nationale fiscale parameters
-- ---------------------------------------------------------------------------

create table if not exists public.tax_parameters (
  year                integer primary key,
  vaa_minimum         numeric not null,
  ref_co2_benzine     numeric not null,
  ref_co2_diesel      numeric not null,
  co2_pct_min         numeric not null,
  co2_pct_max         numeric not null,
  co2_pct_basis       numeric not null,
  co2_pct_per_gram    numeric not null,
  rsz_index           numeric not null,
  rsz_min_maand       numeric not null,
  rsz_min_basis       numeric not null,
  rsz_multiplicator   numeric not null,
  venb_tarief         numeric not null,
  kmo_tarief          numeric not null,
  kmo_min_bezoldiging numeric not null,
  vu_pct_met_kaart    numeric not null,
  vu_pct_zonder_kaart numeric not null,
  updated_at          timestamptz not null default now()
);

create table if not exists public.bestelperiodes (
  code              text primary key,
  label             text not null,
  van               date,
  tot               date,
  rsz_multiplicator numeric not null,
  volgorde          integer not null
);

create table if not exists public.deduction_rules (
  id            bigint generated by default as identity primary key,
  voertuigtype  text not null check (voertuigtype in ('BEV', 'PHEV', 'HEV', 'fossiel')),
  bestelperiode text not null references public.bestelperiodes (code) on update cascade,
  gebruiksjaar  integer,
  aftrek_pct    numeric not null
);

-- gebruiksjaar mag null zijn (= hele gebruiksduur); een gewone unique constraint
-- beschouwt nulls als verschillend, vandaar de coalesce-expressie.
create unique index if not exists deduction_rules_uniek
  on public.deduction_rules (voertuigtype, bestelperiode, coalesce(gebruiksjaar, -1));

create table if not exists public.car_catalog (
  id                bigint generated by default as identity primary key,
  merk              text not null,
  model             text not null,
  voertuigtype      text not null check (voertuigtype in ('BEV', 'PHEV', 'HEV', 'fossiel')),
  brandstof         text not null check (brandstof in ('elektrisch', 'diesel', 'benzine', 'lpg', 'cng')),
  co2               numeric not null,
  cataloguswaarde   numeric not null,
  segment           text,
  populariteit_rang integer,
  opmerking         text,
  image_url         text
);

-- ---------------------------------------------------------------------------
-- Gebruikersdata
-- ---------------------------------------------------------------------------

create table if not exists public.vehicles (
  id                   uuid primary key default gen_random_uuid(),
  omschrijving         text not null,
  werknemer            text,
  kenteken             text,
  categorie            text not null check (categorie in ('vloot', 'kandidaat')),
  merk                 text,
  model                text,
  catalog_id           bigint references public.car_catalog (id) on delete set null,
  voertuigtype         text not null check (voertuigtype in ('BEV', 'PHEV', 'HEV', 'fossiel')),
  brandstof            text not null check (brandstof in ('elektrisch', 'diesel', 'benzine', 'lpg', 'cng')),
  besteldatum          date not null,
  eerste_ingebruikname date not null,
  co2                  numeric not null,
  cataloguswaarde      numeric not null,
  jaarlijkse_autokosten numeric not null,
  aankoopprijs         numeric,
  tankkaart            boolean not null default false,
  beroepsgebruik_pct   numeric not null default 100,
  thuislaadpunt        boolean not null default false,
  km_per_jaar          numeric,
  flex_score           numeric not null default 5,
  restwaarde_score     numeric not null default 5,
  created_at           timestamptz not null default now()
);

create table if not exists public.evaluations (
  id           uuid primary key default gen_random_uuid(),
  titel        text not null,
  vehicle_ids  jsonb not null,
  resultaten   jsonb not null,
  aanbeveling  text not null,
  notitie      text,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Seed referentiedata (spiegelt src/lib/fiscaal/defaults.ts)
-- ---------------------------------------------------------------------------

insert into public.tax_parameters (
  year, vaa_minimum, ref_co2_benzine, ref_co2_diesel, co2_pct_min, co2_pct_max,
  co2_pct_basis, co2_pct_per_gram, rsz_index, rsz_min_maand, rsz_min_basis,
  rsz_multiplicator, venb_tarief, kmo_tarief, kmo_min_bezoldiging,
  vu_pct_met_kaart, vu_pct_zonder_kaart
) values
  (2025, 1650, 71, 59, 4, 18, 5.5, 0.1, 1.5948, 37.33, 33.22, 2.75, 25, 20, 45000, 40, 17),
  (2026, 1690, 70, 58, 4, 18, 5.5, 0.1, 1.6291, 42.34, 33.93, 4.0,  25, 20, 50000, 40, 17),
  (2027, 1690, 70, 58, 4, 18, 5.5, 0.1, 1.6291, 42.34, 33.93, 5.5,  25, 20, 50000, 40, 17),
  (2028, 1690, 70, 58, 4, 18, 5.5, 0.1, 1.6291, 42.34, 33.93, 5.5,  25, 20, 50000, 40, 17),
  (2029, 1690, 70, 58, 4, 18, 5.5, 0.1, 1.6291, 42.34, 33.93, 5.5,  25, 20, 50000, 40, 17),
  (2030, 1690, 70, 58, 4, 18, 5.5, 0.1, 1.6291, 42.34, 33.93, 5.5,  25, 20, 50000, 40, 17),
  (2031, 1690, 70, 58, 4, 18, 5.5, 0.1, 1.6291, 42.34, 33.93, 5.5,  25, 20, 50000, 40, 17)
on conflict (year) do nothing;

insert into public.bestelperiodes (code, label, van, tot, rsz_multiplicator, volgorde) values
  ('voor_07_2023', 'Vóór 1 juli 2023 (gramformule)',   null,         '2023-06-30', 1,   1),
  ('2023H2_2025',  '1 juli 2023 – 31 december 2025',   '2023-07-01', '2025-12-31', 4,   2),
  ('2026',         '1 januari – 31 december 2026',     '2026-01-01', '2026-12-31', 4,   3),
  ('2027',         'Kalenderjaar 2027',                '2027-01-01', '2027-12-31', 5.5, 4),
  ('2028',         'Kalenderjaar 2028',                '2028-01-01', '2028-12-31', 6,   5),
  ('2029',         'Kalenderjaar 2029',                '2029-01-01', '2029-12-31', 6,   6),
  ('2030',         'Kalenderjaar 2030',                '2030-01-01', '2030-12-31', 6,   7),
  ('2031_plus',    'Vanaf 1 januari 2031',             '2031-01-01', null,         6,   8)
on conflict (code) do nothing;

-- BEV behoudt zijn aftrek levenslang (geen gebruiksjaar), met uitdovende
-- percentages naargelang de bestelperiode.
insert into public.deduction_rules (voertuigtype, bestelperiode, gebruiksjaar, aftrek_pct) values
  ('BEV', '2023H2_2025', null, 100),
  ('BEV', '2026',        null, 100),
  ('BEV', '2027',        null, 95),
  ('BEV', '2028',        null, 90),
  ('BEV', '2029',        null, 82.5),
  ('BEV', '2030',        null, 75),
  ('BEV', '2031_plus',   null, 67.5)
on conflict do nothing;

-- Verbrandingsmotoren besteld tussen 1/7/2023 en 31/12/2025: uitdoofkalender
-- per gebruiksjaar. Besteld vanaf 2026: aftrek onmiddellijk op nul.
insert into public.deduction_rules (voertuigtype, bestelperiode, gebruiksjaar, aftrek_pct)
select t.voertuigtype, '2023H2_2025', k.gebruiksjaar, k.aftrek_pct
from (values ('PHEV'), ('HEV'), ('fossiel')) as t (voertuigtype)
cross join (values (2025, 75), (2026, 50), (2027, 25), (2028, 0)) as k (gebruiksjaar, aftrek_pct)
on conflict do nothing;

insert into public.deduction_rules (voertuigtype, bestelperiode, gebruiksjaar, aftrek_pct)
select t.voertuigtype, p.bestelperiode, null, 0
from (values ('PHEV'), ('HEV'), ('fossiel')) as t (voertuigtype)
cross join (values ('2026'), ('2027'), ('2028'), ('2029'), ('2030'), ('2031_plus')) as p (bestelperiode)
on conflict do nothing;

-- De 25 rijen van car_catalog staan bewust niet in deze migratie: ze bestaan
-- alleen in het bestaande project. Exporteer ze daar eenmalig
-- (Table Editor → car_catalog → Export CSV) en importeer ze in een nieuw
-- project. De rest van het schema is hiermee volledig reproduceerbaar.
